name: Python Package CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-python-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        dependencies: ["minimum", "latest"]
        include:
          - dependencies: "minimum"
            deps_spec: "pydantic==2.0.0 aiohttp==3.9.0"
          - dependencies: "latest"
            deps_spec: "pydantic>=2.0 aiohttp>=3.9"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install ${{ matrix.deps_spec }}
        pip install -e ".[dev]"

    - name: Run tests
      run: pytest
